# Generated by Django 2.2.16 on 2022-11-20 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20221120_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальный рейтинг - 1'), django.core.validators.MaxValueValidator(limit_value=10, message='Максимальный рейтинг - 10')], verbose_name='Оценка'),
        ),
    ]
