# Generated by Django 2.2.16 on 2022-11-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_user_third_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='third_name',
        ),
    ]
