# Generated by Django 2.2.16 on 2022-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20221115_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', help_text='Администратор, модератор или обычный пользователь.По умолчанию `user`.', max_length=30, verbose_name='Пользовательская роль'),
        ),
    ]
